trigger:
- master

resources:
  containers:
  - container: debian-stretch
    image: debian:stretch
  - container: debian-buster
    image: debian:buster

jobs:
- job: test
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      jessie:
        containerResource: debian-jessie
      stretch:
        containerResource: debian-stretch
  container: $[ variables['containerResource'] ]
  steps:
    - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      displayName: 'Install rustc'
    - script: |
        export PATH=$PATH:$HOME/.cargo/bin
        cc -v
        cargo test
      displayName: 'cargo test'
