trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
    source ~/.cargo/env
  displayName: 'Install rustc'
- script: cargo build
  displayName: 'cargo build'
- script: cargo test
  displayName: 'cargo test'
