trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- displayName: 'Install rustc'
  script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly

- displayName: 'cargo test'
  script: |
    export PATH=$PATH:$HOME/.cargo/bin
    cargo test
