trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  displayName: 'Install rustc'

- script: |
    export PATH=$PATH:$HOME/.cargo/bin
    export CC=g++
    cargo test
  displayName: 'cargo test'
