version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: sudo apt install cmake
      - run: rustup default nightly
      - run: cargo test
