version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Setup C/C++ toolchain
          command: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install cmake -y
      - run: rustup default nightly
      - run: cargo test
