version: 2.1

jobs:
  "Build and test":
    docker:
      - image: 1.32.0-stretch
    steps:
      - checkout
      - run:
          name: Install rustc
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      - run:
          name: Test
          command: cargo test
